
/* 
✅✅✅tsconfig.json, src and dist
These three are commonly used together in a TypeScript project.


✅✅✅1. tsconfig.json
tsconfig.json is the configuration file for TypeScript.

➡️It tells the TypeScript compiler:
Which files to compile
Which JavaScript version to generate
Which module system to use
Where to put compiled files
How strict type checking should be


Example:
{
  "compilerOptions": {
    "target": "ES2022",
    "module": "NodeNext",
    "strict": true,
    "rootDir": "./src",
    "outDir": "./dist"
  }
}


➡️Important options:
target   → JavaScript version
module   → Module system
strict   → Strict type checking
rootDir  → TypeScript source folder
outDir   → Compiled JavaScript folder




✅✅✅2. src
src means source.
This is where you normally write your TypeScript code.


➡️Project:
project/
├── src/
│   ├── index.ts
│   ├── user.ts
│   └── utils.ts
├── dist/
├── package.json
└── tsconfig.json

➡️For example:
// src/index.ts
const name: string = "Raju";
console.log(name);

So:
src → Your original TypeScript code




✅✅✅3. dist
dist usually means distribution.
It contains the JavaScript files generated by the TypeScript compiler.

➡️If:
src/index.ts
is compiled, you may get:
dist/index.js


➡️For example:
project/
│
├── src/
│   └── index.ts       ← You write this
│
├── dist/
│   └── index.js       ← TypeScript generates this
│
├── package.json
└── tsconfig.json




✅✅4. How They Work Together

The workflow is:

        You write
           ↓
       src/index.ts
           ↓
     TypeScript Compiler
           ↓
       dist/index.js
           ↓
       Node / Browser


➡️Your tsconfig.json connects src and dist:
{
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "./dist"
  }
}

➡️Meaning:
rootDir
   ↓
Where my TypeScript source code is
   ↓
src/


outDir
   ↓
Where compiled JavaScript should go
   ↓
dist/




✅✅5. Compile the Project

From the project root:
npx tsc

TypeScript reads:
tsconfig.json


Then:
src/*.ts
    ↓
   tsc
    ↓
dist/*.js



✅✅6. Example

➡️Before compilation
project/
├── src/
│   └── index.ts
├── dist/
├── package.json
└── tsconfig.json

src/index.ts:
const age: number = 25;
console.log(age);
Run:
npx tsc


➡️After compilation
project/
├── src/
│   └── index.ts
├── dist/
│   └── index.js
├── package.json
└── tsconfig.json

➡️dist/index.js will contain JavaScript similar to:
const age = 25;
console.log(age);

Then run the generated JavaScript:
node dist/index.js
Output:
25






*/